In [1]:
import numpy as np

In [11]:
M = np.array([[1,3,4], [0,5,2], [8,9,3], [2,0,1300]])
v = np.array([[1],[2],[3]])

In [3]:
y = np.array([1,2,3,4,5])

In [7]:
M

array([[1, 3, 4],
       [0, 5, 2],
       [8, 9, 3]])

In [9]:
y

array([1, 2, 3, 4, 5])

In [12]:
M.shape

(4, 3)

In [14]:
y.shape

(5,)

### Vector to Vector Addition

In [18]:
v

array([[1],
       [2],
       [3]])

### Vector to Scalar Multiplication

In [17]:
3 * v

array([[3],
       [6],
       [9]])

### Matrix to Vector Multiplication

In [22]:
M = np.array([[1,3,2], [4,0,1]])
V = np.array([[1],[0],[5]])
M.dot(v)

array([[11],
       [ 9]])

In [23]:
V.shape

(3, 1)

In [24]:
M = np.array([[1,3,2], [4,0,1]])
N = np.array([[1,3],[0,1],[5,2]])
M.dot(N)

array([[11, 10],
       [ 9, 14]])

In [27]:
N.shape

(3, 2)

### Commutativity Properties

In [48]:
A = np.array([[1,3,2], [4,0,1], [2,0,1]])
B = np.array([[1,3, 4],[0,1,5],[5,2,1]])
x = 3
y = 5

In [29]:
x * y == y * x

True

In [30]:
A.dot(B) ==  B.dot(A)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

### Associativity Properties

In [31]:
5 * (x * y) == (5 * x) * y

True

In [46]:
C = np.array([[2,3,2], [4,0,1],[4,0,2]])

In [40]:
D = np.random.randint(5, size=(2,2))
A.dot(B.dot(C)) == (A.dot(B)).dot(C)

array([[ True,  True,  True],
       [ True,  True,  True]])

### Distributative Properties

In [41]:
3 * (x + y) == (x*3 + y*3)

True

In [42]:
D = np.random.randint(34, size=(2,3))

In [49]:
C.dot(A + B) == (C.dot(A) + C.dot(B))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])