In [3]:
import numpy as np

In [7]:
v = np.array([1])
v_vanilla = [1]

In [8]:
v

array([1])

In [9]:
v_vanilla

[1]

In [10]:
M = np.array([[1,3,4], [0,5,2], [8,9,3], [2,0,1300]])
v = np.array([[1],[2],[3]])

In [11]:
y = np.array([1,2,3,4,5])

In [12]:
M

array([[   1,    3,    4],
       [   0,    5,    2],
       [   8,    9,    3],
       [   2,    0, 1300]])

In [13]:
y

array([1, 2, 3, 4, 5])

In [14]:
v

array([[1],
       [2],
       [3]])

In [15]:
M.shape

(4, 3)

In [16]:
y.shape

(5,)

In [17]:
v.shape

(3, 1)

### Vector to Vector Addition

In [19]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
b = 2*b

In [20]:
a + b

array([ 3,  6,  9, 12, 15])

### Vector to Scalar Multiplication

In [21]:
3 * a

array([ 3,  6,  9, 12, 15])

### Matrix to Vector Multiplication

In [22]:
M = np.array([[1,3,2], [4,0,1]])
V = np.array([[1],[0],[5]])
M.dot(v)

array([[13],
       [ 7]])

In [23]:
V.shape

(3, 1)

In [23]:
M = np.array([[1,3,2], [4,0,1]])
N = np.array([[1,3],[0,1],[5,2]])
M.dot(N)

array([[11, 10],
       [ 9, 14]])

In [27]:
N.shape

(3, 2)

### Commutativity Properties

In [24]:
A = np.array([[1,3,2], [4,0,1], [2,0,1]])
B = np.array([[1,3, 4],[0,1,5],[5,2,1]])
x = 3
y = 5

In [25]:
x * y == y * x

True

In [26]:
A.dot(B) ==  B.dot(A)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

### Associativity Properties

In [27]:
5 * (x * y) == (5 * x) * y

True

In [29]:
C = np.array([[2,3,2], [4,0,1],[4,0,2]])

In [30]:
D = np.random.randint(5, size=(2,2))
A.dot(B.dot(C)) == (A.dot(B)).dot(C)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Distributative Properties

In [31]:
3 * (x + y) == (x*3 + y*3)

True

In [32]:
D = np.random.randint(34, size=(2,3))

In [37]:
C

array([[2, 3, 2],
       [4, 0, 1],
       [4, 0, 2]])

In [38]:
C.dot(A + B) == (C.dot(A) + C.dot(B))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [41]:
I = np.eye(3,3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
C.dot(I)

array([[2., 3., 2.],
       [4., 0., 1.],
       [4., 0., 2.]])

In [44]:
y = np.array([1,2,3,4,5])

In [45]:
[x*2 for x in y]

[2, 4, 6, 8, 10]

In [46]:
for i in range(len(y)):
    y[i]+=1

In [47]:
y

array([2, 3, 4, 5, 6])

In [48]:
s = "pattern recognition"

In [58]:
[w for w in y]

[4, 9, 16, 25, 36]

In [59]:
def capitalizer(w):
    return w.upper()

In [60]:
[capitalizer(w) for w in s.split()]

['PATTERN', 'RECOGNITION']